<a href="https://colab.research.google.com/github/Matt-L-053124/FTI-World-Poverty-DSRP/blob/main/Matthew_L_World_Poverty_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
echo "# FTI-World-Poverty-DSRP" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/Matt-L-053124/FTI-World-Poverty-DSRP.git
git push -u origin main

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (107765105.py, line 6)

In [3]:
import pandas as pd

file_path = 'poverty_original.csv'
df = pd.read_csv(file_path)

df.head()

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
0,Albania,1996,national,consumption,2011,1996.0,0.0,0.920669,11.174149,44.618417,...,8.85,10.92,0.270103,0.119104,0.241293,0.928335,3.945872,3.568627,1.889273,1.888889
1,Albania,2002,national,consumption,2011,2002.0,1.0,1.570843,14.132118,49.669635,...,8.83,11.58,0.317390,0.164812,0.268982,1.215056,4.831625,3.979381,2.090253,1.903780
2,Albania,2005,national,consumption,2011,2005.0,1.0,0.860527,8.715685,38.545254,...,10.02,12.78,0.305957,0.154413,0.254529,1.142718,4.662236,3.872727,1.978328,1.957576
3,Albania,2008,national,consumption,2011,2008.0,1.0,0.313650,5.250542,31.110345,...,10.74,13.62,0.299847,0.148893,0.247311,1.114657,4.395911,3.574803,1.956897,1.826772
4,Albania,2012,national,consumption,2011,2012.0,1.0,0.849754,6.182414,34.528906,...,10.52,13.26,0.289605,0.138417,0.249988,1.041193,4.272573,3.632877,1.941435,1.871233

In [4]:
df.describe()

,year,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,headcount_ratio_100,headcount_ratio_1000,headcount_ratio_2000,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
count,4877.000000,4877.000000,4411.000000,4411.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,...,4877.000000,4877.000000,4401.000000,4401.000000,4401.000000,4395.000000,4395.000000,4877.000000,4877.000000,4877.000000
mean,2005.759893,2013.999385,2005.939896,1.639084,11.081565,21.672687,36.538818,3.164721,50.351520,69.105964,...,26.273736,35.110607,0.375645,0.264371,0.327385,1.886528,8.219764,7.424451,2.532256,2.660335
std,9.438782,3.000308,9.497211,1.402898,18.190433,27.104145,33.674140,7.568626,36.002943,34.132391,...,24.171141,30.671393,0.088840,0.140325,0.101136,1.138502,6.018946,42.891943,0.954387,11.785204
min,1967.000000,2011.000000,1967.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.920154,...,1.010000,1.460000,0.177920,0.053563,0.146643,0.596408,2.430173,2.191176,1.475248,1.485294
25%,2000.000000,2011.000000,2000.000000,1.000000,0.278387,0.807877,3.032081,0.044772,10.328433,44.575897,...,8.680000,11.960000,0.308719,0.163090,0.252448,1.154071,4.720943,3.937500,2.017751,1.942113
50%,2007.000000,2011.000000,2007.000000,1.000000,2.041412,9.186717,28.582685,0.371755,55.337658,84.916259,...,16.980000,24.560000,0.355622,0.220968,0.300364,1.465800,6.171947,5.149826,2.290076,2.207904
75%,2013.000000,2017.000000,2014.000000,2.000000,13.390963,34.166712,64.864719,2.158480,85.133887,97.179433,...,35.550000,48.350000,0.427676,0.320859,0.380201,2.152142,9.043292,7.458333,2.780911,2.740385
max,2021.000000,2017.000000,2021.000000,6.000000,96.871427,99.999000,99.999000,79.532619,99.999000,100.000000,...,120.100000,164.700000,0.657556,0.937047,0.815704,8.343586,72.681737,2892.000000,11.491525,809.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Columns: 108 entries, country to p50_p10_ratio
dtypes: float64(103), int64(2), object(3)
memory usage: 4.0+ MB

In [6]:
df.columns

Index(['country', 'year', 'reporting_level', 'welfare_type', 'ppp_version',
       'survey_year', 'survey_comparability',
       'headcount_ratio_international_povline',
       'headcount_ratio_lower_mid_income_povline',
       'headcount_ratio_upper_mid_income_povline',
       ...
       'decile8_thr', 'decile9_thr', 'gini', 'mld', 'polarization',
       'palma_ratio', 's80_s20_ratio', 'p90_p10_ratio', 'p90_p50_ratio',
       'p50_p10_ratio'],
      dtype='object', length=108)

In [13]:
columns_kept = [
    'country', 'year', 'reporting_level', 'welfare_type', 'ppp_version',
    'survey_year', 'survey_comparability', 'headcount_ratio_international_povline',
    'headcount_ratio_lower_mid_income_povline', 'headcount_ratio_upper_mid_income_povline',
    'headcount_ratio_100', 'headcount_ratio_1000', 'headcount_ratio_2000',
    'headcount_ratio_3000', 'headcount_ratio_4000', 'headcount_ratio_40_median',
    'headcount_ratio_50_median', 'headcount_ratio_60_median', 'headcount_international_povline',
    'headcount_lower_mid_income_povline', 'headcount_upper_mid_income_povline',
    'headcount_100', 'headcount_1000', 'headcount_2000', 'headcount_3000', 'headcount_4000',
    'poverty_gap_index_international_povline', 'poverty_gap_index_lower_mid_income_povline',
    'poverty_gap_index_upper_mid_income_povline', 'poverty_gap_index_100',
    'poverty_gap_index_1000', 'poverty_gap_index_2000', 'poverty_gap_index_3000',
    'poverty_gap_index_4000', 'mean', 'median', 'gini', 'mld', 'polarization', 'palma_ratio'
]

df = df[columns_kept]
df

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,poverty_gap_index_1000,poverty_gap_index_2000,poverty_gap_index_3000,poverty_gap_index_4000,mean,median,gini,mld,polarization,palma_ratio
0,Albania,1996,national,consumption,2011,1996.0,0.0,0.920669,11.174149,44.618417,...,38.429134,67.273063,78.128753,83.581605,6.570821,5.774805,0.270103,0.119104,0.241293,0.928335
1,Albania,2002,national,consumption,2011,2002.0,1.0,1.570843,14.132118,49.669635,...,40.271426,67.192763,77.792335,83.289726,6.715828,5.539607,0.317390,0.164812,0.268982,1.215056
2,Albania,2005,national,consumption,2011,2005.0,1.0,0.860527,8.715685,38.545254,...,33.822248,63.027490,74.945700,81.110125,7.591930,6.460357,0.305957,0.154413,0.254529,1.142718
3,Albania,2008,national,consumption,2011,2008.0,1.0,0.313650,5.250542,31.110345,...,29.439467,60.024798,72.841826,79.482429,8.314345,6.957659,0.299847,0.148893,0.247311,1.114657
4,Albania,2012,national,consumption,2011,2012.0,1.0,0.849754,6.182414,34.528906,...,31.062755,61.333158,73.871346,80.347266,7.882867,6.825289,0.289605,0.138417,0.249988,1.041193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,Zambia,2010,national,consumption,2017,2010.0,4.0,68.456606,82.885088,93.044964,...,77.516011,87.790694,91.649466,93.667877,2.607178,1.353084,0.556215,0.539135,0.536149,4.278696
4873,Zambia,2015,national,consumption,2017,2015.0,4.0,61.352160,77.548045,90.747141,...,74.293875,85.888877,90.329245,92.652525,3.012274,1.570981,0.571361,0.604667,0.613181,4.995829
4874,Zimbabwe,2011,national,consumption,2017,2011.0,0.0,21.580063,47.857143,77.945113,...,53.901382,74.193975,82.234772,86.494285,5.459878,3.798868,0.431536,0.311153,0.388356,2.207938
4875,Zimbabwe,2017,national,consumption,2017,2017.0,0.0,34.206046,61.583570,84.109019,...,61.408649,78.921468,85.638964,89.124044,4.409205,2.874558,0.443371,0.322848,0.416694,2.307359
4876,Zimbabwe,2019,national,consumption,2017,2019.0,0.0,39.754533,64.509857,85.016315,...,63.420138,79.385502,85.694379,89.059476,4.500192,2.654817,0.502565,0.427862,0.463899,NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Data columns (total 40 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   country                                     4877 non-null   object
 1   year                                        4877 non-null   int64
 2   reporting_level                             4411 non-null   object
 3   welfare_type                                4411 non-null   object
 4   ppp_version                                 4877 non-null   int64
 5   survey_year                                 4411 non-null   float64
 6   survey_comparability                        4411 non-null   float64
 7   headcount_ratio_international_povline       4877 non-null   float64
 8   headcount_ratio_lower_mid_income_povline    4877 non-null   float64
 9   headcount_ratio_upper_mid_income_povline    4877 non-null   float64
 10  headcount_ratio_100                         4877 non-null   float64
 11  headcount_ratio_1000                        4877 non-null   float64
 12  headcount_ratio_2000                        4877 non-null   float64
 13  headcount_ratio_3000                        4877 non-null   float64
 14  headcount_ratio_4000                        4877 non-null   float64
 15  headcount_ratio_40_median                   4411 non-null   float64
 16  headcount_ratio_50_median                   4411 non-null   float64
 17  headcount_ratio_60_median                   4411 non-null   float64
 18  headcount_international_povline             4877 non-null   float64
 19  headcount_lower_mid_income_povline          4877 non-null   float64
 20  headcount_upper_mid_income_povline          4877 non-null   float64
 21  headcount_100                               4877 non-null   float64
 22  headcount_1000                              4877 non-null   float64
 23  headcount_2000                              4877 non-null   float64
 24  headcount_3000                              4877 non-null   float64
 25  headcount_4000                              4877 non-null   float64
 26  poverty_gap_index_international_povline     4877 non-null   float64
 27  poverty_gap_index_lower_mid_income_povline  4877 non-null   float64
 28  poverty_gap_index_upper_mid_income_povline  4877 non-null   float64
 29  poverty_gap_index_100                       4877 non-null   float64
 30  poverty_gap_index_1000                      4877 non-null   float64
 31  poverty_gap_index_2000                      4877 non-null   float64
 32  poverty_gap_index_3000                      4877 non-null   float64
 33  poverty_gap_index_4000                      4877 non-null   float64
 34  mean                                        4877 non-null   float64
 35  median                                      4877 non-null   float64
 36  gini                                        4401 non-null   float64
 37  mld                                         4401 non-null   float64
 38  polarization                                4401 non-null   float64
 39  palma_ratio                                 4395 non-null   float64
dtypes: float64(35), int64(2), object(3)
memory usage: 1.5+ MB